apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - name: hello-world-app
        image: {{REGISTRY_NAME}}.azurecr.io/mygradezimage:{{GITHUB_SHA}}
        ports:
        - containerPort: 8080
